### PR TITLE
fix: forward host header to dynamic source endpoint

### PR DESCRIPTION
**Pull request by chenyuncai**
Try to get right host in danymic source eventhandler and give right right urls back.

It's useful in some saas platform with custom domain support, The sitemap need to be different for each Tenant

### CODE REVIEW

**Comment by chenyuncai** [comment]
Hi @harlan-zw , is this PR useful or anything I need change?

**Comment by harlan-zw** [comment]
Hi @chenyuncai, thank you for the PR :raised_hands:!

There is one thing I need to investigate before merging this which is blocking it. I believe there is a way to call fetch where it will automatically forward these headers. I think it may be the `event.fetch` or something.

We should use as it will fix the problem for all use cases not just the `host`.

**Comment by chenyuncai** [comment]
Yes, that's right, maybe we should send all headers to self event handler, and only safe headers to third-party sources. 

Thanks for your response.

**Comment by harlan-zw** [comment]
That also does seem reasonable :thinking: I'll have a think during the day and revisit this tonight

**Comment by harlan-zw** [comment]
Thanks for the PR, I've merged this into 5.2.0 with a minor fix to avoid empty Host headers being passed.

**Pull request merged**
