### PR TITLE
feat: `nuxt-i18n-micro` module integration

### PR DESCRIPTION
**Pull request by harlan-zw**
### 🔗 Linked issue

https://github.com/s00d/nuxt-i18n-micro/issues/11

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

As the i18n config has an identical signature we can support the https://github.com/s00d/nuxt-i18n-micro module out of the box without any extra effort :crossed_fingers:

### CODE REVIEW

**Comment by genu** [comment]
@harlan-zw is a similar change required here?

https://github.com/harlan-zw/nuxt-seo/blob/bc1dc0b4263adcf90d8df372c4b4eb21a937ba6e/src/module.ts#L143C5-L146C6

**Comment by harlan-zw** [comment]
Thanks for the review @genu, I'm only considering sitemap integration with this module at the moment.

**Comment by genu** [comment]
I see, but wouldn't it cause issue when using the main seo module?

For instance, it will polyfill the i18n composable when it should not, since its provided by `nuxt-i18n-micro`.

Nuxt throws errors about duplicate composables when using together.

**Comment by harlan-zw** [comment]
Hmm good point but it's a warning that is thrown so not a big deal, the pollyfills should be registered with low priority though.

Having to support nuxt-i18n-micro in all SEO modules is not something I have capacity for at the moment so if this is a blocker then we may consider closing this PR.

**Comment by genu** [comment]
Hmm, I can test a little bit more on my end, as I noticed the polyfill is indeed used instead of the i18n-micro composable. 

Maybe the order in the modules array affects this? 🤔

**Pull request merged**
